version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: flowforge-nexus-postgres
    environment:
      POSTGRES_DB: flowforge_nexus
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - flowforge-network

  # Redis for caching and state management
  redis:
    image: redis:7-alpine
    container_name: flowforge-nexus-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - flowforge-network

  # NATS for messaging
  nats:
    image: nats:2.9-alpine
    container_name: flowforge-nexus-nats
    ports:
      - "4222:4222"
      - "8222:8222"
    command: ["-js", "-m", "8222"]
    networks:
      - flowforge-network

  # Prometheus for metrics
  prometheus:
    image: prom/prometheus:latest
    container_name: flowforge-nexus-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    networks:
      - flowforge-network

  # Grafana for visualization
  grafana:
    image: grafana/grafana:latest
    container_name: flowforge-nexus-grafana
    ports:
      - "3001:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/dashboards:/etc/grafana/provisioning/dashboards
      - ./monitoring/grafana/datasources:/etc/grafana/provisioning/datasources
    networks:
      - flowforge-network

  # Jaeger for distributed tracing
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: flowforge-nexus-jaeger
    ports:
      - "16686:16686"
      - "14268:14268"
    environment:
      COLLECTOR_OTLP_ENABLED: true
    networks:
      - flowforge-network

  # FlowForge Nexus Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flowforge-nexus-app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: password
      DB_DATABASE: flowforge_nexus
      REDIS_HOST: redis
      REDIS_PORT: 6379
      NATS_URL: nats://nats:4222
      PROMETHEUS_URL: http://prometheus:9090
      JAEGER_URL: http://jaeger:14268
    depends_on:
      - postgres
      - redis
      - nats
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - flowforge-network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  prometheus_data:
  grafana_data:

networks:
  flowforge-network:
    driver: bridge
